---
title: "Whale Abundance"
author: "Meghan Roberts"
date: "2024-06-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(ggplot2)
library(janitor)
library(tidyr)
```

```{r}
abundance<-read_csv(here("data", "RAMP_Whales_over_time.csv")) %>% clean_names()
abundance$zone <- as.factor(abundance$zone)
abundance$date <- as.Date(abundance$date)
abundance$abundance_level_numeric <- as.numeric(factor(abundance$abundance_level, levels = c("minimal", "moderate", "abundant"), labels = c(1, 2, 3)))

```

```{r}
abundance <- abundance %>%
  mutate(year = format(date, "%Y")) %>% 
  mutate(month_day = format(date, "%m-%d"))

month_day_labels <- c("March 1-31", "April 1-15", "April 16-30", "May 1-31")
zone_labels <- c("1"="Zone 1", "2"="Zone 2","3" ="Zone 3","4" ="Zone 4","5" ="Zone 5","6"= "Zone 6")
year_colors <- c("2020" = "#4dbd05", "2021" = "#1fbeb8", "2022" = "#0088c9", "2023"="#6563c4", "2024"="#9b45a3")

ggplot(abundance, aes(x = month_day, y = abundance_level_numeric, color = year)) +
  geom_jitter(size = 3, position = position_jitter(width = 0.05), alpha = 0.8) +  # Adding jitter
  labs(x = "",
       y = "Abundance Level",
       color = "Year") +
  scale_color_manual(values = year_colors) +  # Use custom colors
  facet_wrap(~ zone, scales = "fixed", labeller = labeller(zone = as_labeller(zone_labels)), ncol = 2) +
  scale_y_continuous(breaks = 1:3, labels = c("minimal", "moderate", "abundant")) +
  scale_x_discrete(labels = month_day_labels) +
  theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        panel.spacing = unit(30, "pt"), #adjust space between plots
        axis.text.x = element_text(angle = 45, hjust = 1, size = 12),  # Adjust text size here
        axis.text.y = element_text(size = 12),  # Adjust text size here
        axis.title = element_text(size = 14),  # Adjust text size here
        legend.title = element_text(size = 14),  # Adjust legend title text size here
        legend.text = element_text(size = 12),  # Adjust legend text size here
        strip.text = element_text(size = 12))

ggsave(here("plots", "whale_abundance_by_zone.jpg"), width=8, height=9)

```
#Figure with ship strikes and whale abundance
```{r}
ship_strikes<-read_csv(here("data", "Old_WCR Vessel Collisions 1980-2023 (11-1-23).csv")) %>% clean_names() %>% filter(observation_year %in% 2020:2023) %>% filter(state=="CA") %>% filter(common_name!="Humpback Whale") 
ship_strikes<-ship_strikes%>% mutate(observation_date=as.Date(ship_strikes$observation_date, format = "%m/%d/%Y"))%>%
  mutate(year_month = format(observation_date, "%Y-%m"))

monthly_counts <- ship_strikes %>%
  group_by(year_month, common_name) %>%
  summarise(count = n(), .groups = 'drop')
# %>% 
#   mutate(year_month=as.Date(monthly_counts$year_month, format="%Y/%m"))
  
# Generate a sequence of months
start_date <- ymd("2020-01-01")
end_date <- ymd("2023-12-01")
date_seq <- seq.Date(from = start_date, to = end_date, by = "month")
year_month <- format(date_seq, "%Y-%m")
# Convert to year_month format
year_month <- format(date_seq, "%Y-%m")  

month_year_labels <- c("August 2020", "September 2020", "April 2021", "May 2021", "June 2021", "July 2021", "August 2021", "April 2022", "May 2022", "March 2023", "April 2023", "May 2023", "June 2023")  
whale_colors <- c("Fin Whale" = "#4dbd05", "Gray Whale" = "#0088c9", "Unidentified Whale"="#9b45a3")
  
ggplot(monthly_counts, aes(x = year_month, y = count, fill = common_name)) +
  geom_bar(stat = "identity") +
  # geom_bar_pattern(stat = "identity", pattern_density = 0.1) +
  labs(x = "Observation Date", y = "Number of Individuals", fill = "") +  
  scale_x_discrete(labels = month_year_labels) +
  scale_fill_manual(values = whale_colors) +  # Use custom colors
  theme_minimal()+
    theme(panel.grid.minor = element_blank(),
        panel.spacing = unit(30, "pt"), #adjust space between plots
        axis.text.x = element_text(angle = 45, hjust = 1, size = 12),,  # Adjust text size here
        axis.text.y = element_text(size = 12),  # Adjust text size here
        axis.title = element_text(size = 14),  # Adjust text size here
        legend.title = element_text(size = 14),  # Adjust legend title text size here
        legend.text = element_text(size = 12),  # Adjust legend text size here
        strip.text = element_text(size = 12))

ggsave(here("plots", "ship_strikes.jpg"), width=8, height=7)
```


